import 'package:flutter/material.dart';

import 'souq_models.dart';

class SouqCatalog {
  static const cars = 'cars';

  static const all = <SouqCategory>[
    SouqCategory(
      id: cars,
      nameEn: 'Cars',
      nameAr: 'سيارات',
      icon: Icons.directions_car_rounded,
      gradient: [Color(0xFF0B3D2A), Color(0xFF22C55E)],
      photoTipsEn: 'Front, back, both sides, interior, dashboard/odometer, engine.',
      photoTipsAr: 'أمام، خلف، الجانبين، الداخل، العداد، المحرك.',
      subcategories: [
        SouqSubcategory(id: 'sedan', nameEn: 'Sedan', nameAr: 'سيدان'),
        SouqSubcategory(id: 'suv', nameEn: 'SUV', nameAr: 'دفع رباعي'),
        SouqSubcategory(id: 'pickup', nameEn: 'Pickup', nameAr: 'بيك أب'),
        SouqSubcategory(id: 'hatchback', nameEn: 'Hatchback', nameAr: 'هاتشباك'),
        SouqSubcategory(id: 'coupe', nameEn: 'Coupe', nameAr: 'كوبيه'),
        SouqSubcategory(id: 'van', nameEn: 'Van/Bus', nameAr: 'فان / باص'),
        SouqSubcategory(id: 'classic', nameEn: 'Classic', nameAr: 'كلاسيك'),
        SouqSubcategory(id: 'parts', nameEn: 'Spare Parts', nameAr: 'قطع غيار'),
        SouqSubcategory(id: 'accessories', nameEn: 'Accessories', nameAr: 'إكسسوارات'),
      ],
      fields: [
        AttributeField(
          key: 'make',
          labelEn: 'Make',
          labelAr: 'الشركة',
          type: AttributeType.dropdown,
          options: carMakes,
        ),
        AttributeField(
          key: 'model',
          labelEn: 'Model',
          labelAr: 'الموديل',
          type: AttributeType.text,
          dependsOn: 'make',
        ),
        AttributeField(
          key: 'year',
          labelEn: 'Year',
          labelAr: 'السنة',
          type: AttributeType.year,
        ),
        AttributeField(
          key: 'mileage',
          labelEn: 'Mileage',
          labelAr: 'العداد',
          type: AttributeType.number,
          unit: 'km',
        ),
        AttributeField(
          key: 'transmission',
          labelEn: 'Transmission',
          labelAr: 'القير',
          type: AttributeType.chips,
          options: ['Automatic', 'Manual'],
        ),
        AttributeField(
          key: 'fuel',
          labelEn: 'Fuel',
          labelAr: 'الوقود',
          type: AttributeType.chips,
          options: ['Petrol', 'Diesel', 'Hybrid', 'Electric'],
        ),
        AttributeField(
          key: 'bodyType',
          labelEn: 'Body type',
          labelAr: 'الهيكل',
          type: AttributeType.dropdown,
          options: ['Sedan', 'SUV', 'Pickup', 'Hatchback', 'Coupe', 'Van/Bus'],
        ),
        AttributeField(
          key: 'color',
          labelEn: 'Color',
          labelAr: 'اللون',
          type: AttributeType.color,
          options: [
            'White',
            'Black',
            'Silver',
            'Grey',
            'Blue',
            'Red',
            'Green',
            'Beige',
            'Brown',
          ],
        ),
        AttributeField(
          key: 'engine',
          labelEn: 'Engine size',
          labelAr: 'المحرك',
          type: AttributeType.text,
        ),
        AttributeField(
          key: 'origin',
          labelEn: 'Origin spec',
          labelAr: 'المواصفات',
          type: AttributeType.chips,
          options: ['Saudi', 'GCC', 'American', 'European', 'Other'],
        ),
        AttributeField(
          key: 'sellerType',
          labelEn: 'Seller type',
          labelAr: 'نوع البائع',
          type: AttributeType.chips,
          options: ['Owner', 'Dealer'],
        ),
      ],
    ),
    SouqCategory(
      id: 'mobiles',
      nameEn: 'Mobiles & Tablets',
      nameAr: 'جوالات وتابلت',
      icon: Icons.smartphone_rounded,
      gradient: [Color(0xFF1A1410), Color(0xFFD4A017)],
      photoTipsEn: 'Front, back, ports, any scratches, box if you have it.',
      photoTipsAr: 'أمام، خلف، المنافذ، الخدوش، العلبة إن وجدت.',
      subcategories: [
        SouqSubcategory(id: 'iphone', nameEn: 'iPhone', nameAr: 'آيفون'),
        SouqSubcategory(id: 'samsung', nameEn: 'Samsung', nameAr: 'سامسونج'),
        SouqSubcategory(id: 'phones', nameEn: 'Other Phones', nameAr: 'جوالات أخرى'),
        SouqSubcategory(id: 'tablets', nameEn: 'Tablets', nameAr: 'أجهزة لوحية'),
        SouqSubcategory(id: 'mobile-acc', nameEn: 'Accessories', nameAr: 'إكسسوارات'),
        SouqSubcategory(id: 'watches', nameEn: 'Smart Watches', nameAr: 'ساعات ذكية'),
      ],
      fields: [
        AttributeField(key: 'brand', labelEn: 'Brand', labelAr: 'الشركة', type: AttributeType.dropdown, options: ['Apple', 'Samsung', 'Huawei', 'Xiaomi', 'Other']),
        AttributeField(key: 'model', labelEn: 'Model', labelAr: 'الموديل', type: AttributeType.text),
        AttributeField(key: 'storage', labelEn: 'Storage', labelAr: 'التخزين', type: AttributeType.chips, options: ['64 GB', '128 GB', '256 GB', '512 GB', '1 TB']),
        AttributeField(key: 'color', labelEn: 'Color', labelAr: 'اللون', type: AttributeType.color, options: ['Black', 'White', 'Blue', 'Gold', 'Green', 'Purple']),
        AttributeField(key: 'battery', labelEn: 'Battery health %', labelAr: 'صحة البطارية', type: AttributeType.number, unit: '%'),
        AttributeField(key: 'warranty', labelEn: 'Warranty', labelAr: 'الضمان', type: AttributeType.toggle),
      ],
    ),
    SouqCategory(
      id: 'electronics',
      nameEn: 'Electronics',
      nameAr: 'إلكترونيات',
      icon: Icons.laptop_rounded,
      gradient: [Color(0xFF12355B), Color(0xFF38BDF8)],
      photoTipsEn: 'Device, ports, screen on, serial sticker if visible.',
      photoTipsAr: 'الجهاز، المنافذ، الشاشة تعمل، الملصق إن ظهر.',
      subcategories: [
        SouqSubcategory(id: 'laptops', nameEn: 'Laptops', nameAr: 'لابتوب'),
        SouqSubcategory(id: 'desktops', nameEn: 'Desktops', nameAr: 'كمبيوتر'),
        SouqSubcategory(id: 'tvs', nameEn: 'TVs', nameAr: 'تلفزيونات'),
        SouqSubcategory(id: 'cameras', nameEn: 'Cameras', nameAr: 'كاميرات'),
        SouqSubcategory(id: 'audio', nameEn: 'Audio', nameAr: 'صوتيات'),
        SouqSubcategory(id: 'gaming', nameEn: 'Gaming', nameAr: 'ألعاب'),
      ],
      fields: defaultFields,
    ),
    SouqCategory(
      id: 'furniture',
      nameEn: 'Furniture & Home',
      nameAr: 'أثاث ومنزل',
      icon: Icons.chair_rounded,
      gradient: [Color(0xFF5C3A1A), Color(0xFFE8B86D)],
      photoTipsEn: 'Full piece, close-up of wear, size next to a door or person.',
      photoTipsAr: 'القطعة كاملة، آثار الاستخدام، الحجم بجانب باب.',
      subcategories: [
        SouqSubcategory(id: 'living', nameEn: 'Living Room', nameAr: 'مجلس'),
        SouqSubcategory(id: 'bedroom', nameEn: 'Bedroom', nameAr: 'غرفة نوم'),
        SouqSubcategory(id: 'kitchen', nameEn: 'Kitchen & Dining', nameAr: 'مطبخ'),
        SouqSubcategory(id: 'office', nameEn: 'Office', nameAr: 'مكتب'),
        SouqSubcategory(id: 'decor', nameEn: 'Décor', nameAr: 'ديكور'),
        SouqSubcategory(id: 'outdoor', nameEn: 'Outdoor', nameAr: 'خارجي'),
      ],
      fields: defaultFields,
    ),
    SouqCategory(
      id: 'appliances',
      nameEn: 'Home Appliances',
      nameAr: 'أجهزة منزلية',
      icon: Icons.kitchen_rounded,
      gradient: [Color(0xFF0F4C5C), Color(0xFF2DD4BF)],
      photoTipsEn: 'Front, model sticker, any dents.',
      photoTipsAr: 'الأمام، ملصق الموديل، أي خدوش.',
      subcategories: [
        SouqSubcategory(id: 'ac', nameEn: 'ACs', nameAr: 'مكيفات'),
        SouqSubcategory(id: 'fridges', nameEn: 'Fridges', nameAr: 'ثلاجات'),
        SouqSubcategory(id: 'washers', nameEn: 'Washers', nameAr: 'غسالات'),
        SouqSubcategory(id: 'kitchen-app', nameEn: 'Kitchen Appliances', nameAr: 'أجهزة مطبخ'),
        SouqSubcategory(id: 'small-app', nameEn: 'Small Appliances', nameAr: 'أجهزة صغيرة'),
      ],
      fields: defaultFields,
    ),
    SouqCategory(
      id: 'fashion',
      nameEn: 'Fashion',
      nameAr: 'أزياء',
      icon: Icons.checkroom_rounded,
      gradient: [Color(0xFF6B1D3A), Color(0xFFF472B6)],
      photoTipsEn: 'On a hanger or worn, labels, any defects.',
      photoTipsAr: 'على علاقة أو مرتدى، البطاقات، العيوب.',
      subcategories: [
        SouqSubcategory(id: 'men', nameEn: 'Men', nameAr: 'رجالي'),
        SouqSubcategory(id: 'women', nameEn: 'Women', nameAr: 'نسائي'),
        SouqSubcategory(id: 'kids-fashion', nameEn: 'Kids', nameAr: 'أطفال'),
        SouqSubcategory(id: 'watches-f', nameEn: 'Watches', nameAr: 'ساعات'),
        SouqSubcategory(id: 'bags', nameEn: 'Bags', nameAr: 'شنط'),
        SouqSubcategory(id: 'perfumes', nameEn: 'Perfumes', nameAr: 'عطور'),
        SouqSubcategory(id: 'jewelry', nameEn: 'Jewelry', nameAr: 'مجوهرات'),
      ],
      fields: defaultFields,
    ),
    SouqCategory(
      id: 'realestate',
      nameEn: 'Real Estate',
      nameAr: 'عقارات',
      icon: Icons.apartment_rounded,
      gradient: [Color(0xFF3A2712), Color(0xFFC9A227)],
      photoTipsEn: 'Facade, living areas, kitchen, rooms, view.',
      photoTipsAr: 'الواجهة، المجالس، المطبخ، الغرف، الإطلالة.',
      subcategories: [
        SouqSubcategory(id: 'apt', nameEn: 'Apartments', nameAr: 'شقق'),
        SouqSubcategory(id: 'villa', nameEn: 'Villas', nameAr: 'فلل'),
        SouqSubcategory(id: 'land', nameEn: 'Land', nameAr: 'أراضي'),
        SouqSubcategory(id: 'shops', nameEn: 'Shops', nameAr: 'محلات'),
        SouqSubcategory(id: 'rent', nameEn: 'For Rent', nameAr: 'للإيجار'),
      ],
      fields: [
        AttributeField(key: 'type', labelEn: 'Type', labelAr: 'النوع', type: AttributeType.chips, options: ['Apartment', 'Villa', 'Land', 'Shop']),
        AttributeField(key: 'area', labelEn: 'Area', labelAr: 'المساحة', type: AttributeType.number, unit: 'm²'),
        AttributeField(key: 'rooms', labelEn: 'Rooms', labelAr: 'غرف', type: AttributeType.number),
        AttributeField(key: 'baths', labelEn: 'Bathrooms', labelAr: 'دورات مياه', type: AttributeType.number),
        AttributeField(key: 'furnished', labelEn: 'Furnished', labelAr: 'مفروش', type: AttributeType.toggle),
        AttributeField(key: 'offer', labelEn: 'Offer', labelAr: 'العرض', type: AttributeType.chips, options: ['For sale', 'For rent']),
      ],
    ),
    SouqCategory(
      id: 'sports',
      nameEn: 'Sports & Outdoors',
      nameAr: 'رياضة',
      icon: Icons.sports_soccer_rounded,
      gradient: [Color(0xFF14532D), Color(0xFF84CC16)],
      photoTipsEn: 'Full item, serial if any, wear on grips or tires.',
      photoTipsAr: 'القطعة كاملة، الرقم إن وجد، آثار الاستخدام.',
      subcategories: [
        SouqSubcategory(id: 'bikes', nameEn: 'Bicycles', nameAr: 'دراجات'),
        SouqSubcategory(id: 'fitness', nameEn: 'Fitness Equipment', nameAr: 'لياقة'),
        SouqSubcategory(id: 'camping', nameEn: 'Camping', nameAr: 'تخييم'),
        SouqSubcategory(id: 'hunt', nameEn: 'Hunting & Fishing', nameAr: 'صيد'),
      ],
      fields: defaultFields,
    ),
    SouqCategory(
      id: 'animals',
      nameEn: 'Animals & Pets',
      nameAr: 'حيوانات',
      icon: Icons.pets_rounded,
      gradient: [Color(0xFF5C3D1E), Color(0xFFE0A84A)],
      photoTipsEn: 'Clear photos of the animal, any papers.',
      photoTipsAr: 'صور واضحة، الأوراق إن وجدت.',
      subcategories: [
        SouqSubcategory(id: 'camels', nameEn: 'Camels', nameAr: 'إبل'),
        SouqSubcategory(id: 'sheep', nameEn: 'Sheep & Goats', nameAr: 'أغنام'),
        SouqSubcategory(id: 'birds', nameEn: 'Birds', nameAr: 'طيور'),
        SouqSubcategory(id: 'cats', nameEn: 'Cats', nameAr: 'قطط'),
        SouqSubcategory(id: 'dogs', nameEn: 'Dogs', nameAr: 'كلاب'),
        SouqSubcategory(id: 'horses', nameEn: 'Horses', nameAr: 'خيل'),
        SouqSubcategory(id: 'supplies', nameEn: 'Supplies', nameAr: 'مستلزمات'),
      ],
      fields: [
        AttributeField(key: 'type', labelEn: 'Type', labelAr: 'النوع', type: AttributeType.text),
        AttributeField(key: 'breed', labelEn: 'Breed', labelAr: 'السلالة', type: AttributeType.text),
        AttributeField(key: 'age', labelEn: 'Age', labelAr: 'العمر', type: AttributeType.text),
        AttributeField(key: 'gender', labelEn: 'Gender', labelAr: 'الجنس', type: AttributeType.chips, options: ['Male', 'Female']),
      ],
    ),
    SouqCategory(
      id: 'kids',
      nameEn: 'Kids & Baby',
      nameAr: 'أطفال',
      icon: Icons.child_friendly_rounded,
      gradient: [Color(0xFF9A4A1C), Color(0xFFFBBF24)],
      photoTipsEn: 'Item open and folded, labels, wear.',
      photoTipsAr: 'مفتوح ومطوي، البطاقات، الاستخدام.',
      subcategories: [
        SouqSubcategory(id: 'strollers', nameEn: 'Strollers', nameAr: 'عربات'),
        SouqSubcategory(id: 'seats', nameEn: 'Car Seats', nameAr: 'مقاعد سيارة'),
        SouqSubcategory(id: 'toys', nameEn: 'Toys', nameAr: 'ألعاب'),
        SouqSubcategory(id: 'kids-clothes', nameEn: 'Clothing', nameAr: 'ملابس'),
      ],
      fields: defaultFields,
    ),
    SouqCategory(
      id: 'books',
      nameEn: 'Books & Hobbies',
      nameAr: 'كتب وهوايات',
      icon: Icons.menu_book_rounded,
      gradient: [Color(0xFF3B2A1E), Color(0xFFC4A574)],
      photoTipsEn: 'Cover, spine, any notes or damage.',
      photoTipsAr: 'الغلاف، الكعب، أي كتابة أو تلف.',
      subcategories: [
        SouqSubcategory(id: 'books', nameEn: 'Books', nameAr: 'كتب'),
        SouqSubcategory(id: 'music', nameEn: 'Musical Instruments', nameAr: 'آلات موسيقية'),
        SouqSubcategory(id: 'collect', nameEn: 'Collectibles', nameAr: 'مقتنيات'),
        SouqSubcategory(id: 'art', nameEn: 'Art', nameAr: 'فن'),
      ],
      fields: defaultFields,
    ),
    SouqCategory(
      id: 'tools',
      nameEn: 'Tools & Equipment',
      nameAr: 'عدد ومعدات',
      icon: Icons.handyman_rounded,
      gradient: [Color(0xFF3F2A24), Color(0xFFEF4444)],
      photoTipsEn: 'Kit spread out, brand plates, hours if a generator.',
      photoTipsAr: 'العدة كاملة، اللوحات، ساعات التشغيل.',
      subcategories: [
        SouqSubcategory(id: 'power', nameEn: 'Power Tools', nameAr: 'عدد كهربائية'),
        SouqSubcategory(id: 'heavy', nameEn: 'Heavy Equipment', nameAr: 'معدات ثقيلة'),
        SouqSubcategory(id: 'generators', nameEn: 'Generators', nameAr: 'مولدات'),
      ],
      fields: defaultFields,
    ),
    SouqCategory(
      id: 'motors',
      nameEn: 'Motorcycles & Boats',
      nameAr: 'دراجات وقوارب',
      icon: Icons.two_wheeler_rounded,
      gradient: [Color(0xFF0F2E24), Color(0xFFD97706)],
      photoTipsEn: 'Both sides, dash, engine, hull if a boat.',
      photoTipsAr: 'الجانبين، العداد، المحرك، الهيكل للقوارب.',
      subcategories: [
        SouqSubcategory(id: 'moto', nameEn: 'Motorcycles', nameAr: 'دراجات نارية'),
        SouqSubcategory(id: 'atv', nameEn: 'ATVs', nameAr: 'رباعيات'),
        SouqSubcategory(id: 'boats', nameEn: 'Boats', nameAr: 'قوارب'),
        SouqSubcategory(id: 'jetski', nameEn: 'Jet Skis', nameAr: 'جيت سكي'),
      ],
      fields: defaultFields,
    ),
    SouqCategory(
      id: 'services',
      nameEn: 'Services',
      nameAr: 'خدمات',
      icon: Icons.home_repair_service_rounded,
      gradient: [Color(0xFF134E4A), Color(0xFF5EEAD4)],
      photosRequired: false,
      photoTipsEn: 'Optional photos of past work.',
      photoTipsAr: 'صور أعمال سابقة اختيارية.',
      subcategories: [
        SouqSubcategory(id: 'moving', nameEn: 'Moving', nameAr: 'نقل عفش'),
        SouqSubcategory(id: 'maint', nameEn: 'Maintenance', nameAr: 'صيانة'),
        SouqSubcategory(id: 'tutor', nameEn: 'Tutoring', nameAr: 'دروس'),
        SouqSubcategory(id: 'other-svc', nameEn: 'Other', nameAr: 'أخرى'),
      ],
      fields: defaultFields,
    ),
    SouqCategory(
      id: 'other',
      nameEn: 'Other',
      nameAr: 'أخرى',
      icon: Icons.inventory_2_rounded,
      gradient: [Color(0xFF2A2622), Color(0xFF8A8278)],
      photoTipsEn: 'Show the item clearly from a few angles.',
      photoTipsAr: 'صور واضحة من عدة زوايا.',
      subcategories: [
        SouqSubcategory(id: 'anything', nameEn: 'Anything else', nameAr: 'أي شيء'),
      ],
      fields: defaultFields,
    ),
  ];

  static const defaultFields = <AttributeField>[];

  static const carMakes = [
    'Toyota',
    'Hyundai',
    'Nissan',
    'Lexus',
    'Ford',
    'Chevrolet',
    'Kia',
    'Mercedes',
    'BMW',
    'GMC',
    'Honda',
    'Mazda',
    'Isuzu',
    'Jeep',
    'Volkswagen',
    'Dodge',
    'Mitsubishi',
    'Land Rover',
    'Porsche',
    'Audi',
    'Haval',
    'Chery',
    'MG',
    'Genesis',
    'Cadillac',
    'Infiniti',
    'BYD',
    'Other',
  ];

  static SouqCategory byId(String id) =>
      all.firstWhere((c) => c.id == id, orElse: () => all.last);

  static Color colorForMake(String? make) {
    return switch ((make ?? '').toLowerCase()) {
      'toyota' => const Color(0xFFEB0A1E),
      'hyundai' => const Color(0xFF002C5F),
      'nissan' => const Color(0xFFC3002F),
      'lexus' => const Color(0xFF8A5E2E),
      'ford' => const Color(0xFF003478),
      'chevrolet' => const Color(0xFFD4A017),
      'kia' => const Color(0xFF05141F),
      'mercedes' => const Color(0xFF1B1916),
      'bmw' => const Color(0xFF1C69D4),
      'gmc' => const Color(0xFFA6192E),
      'honda' => const Color(0xFFE40521),
      'mazda' => const Color(0xFF910A2D),
      'isuzu' => const Color(0xFFED1C24),
      'jeep' => const Color(0xFF3D5C3A),
      'volkswagen' => const Color(0xFF001E50),
      _ => const Color(0xFF1E7A4C),
    };
  }
}
